language: java
jdk:
  - openjdk11
services:
  - docker

after_success:
  - mvn -DrepoToken=$COVERALLS_TOKEN coveralls:report

deploy:
  - mvn dockerfile:push -Ddockerfile.username=$DOCKER_USER -Ddockerfile.password=$DOCKER_PASSWORD
