sudo: required
language: java
jdk:
  - openjdk11
services:
  - docker
cache:
  directories:
  - $HOME/.m2
install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.zip
  - unzip -qq apache-maven-3.6.1-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.6.1
  - export PATH=$M2_HOME/bin:$PATH
  - pip install --user awscli
script:
  - mvn --no-transfer-progress clean install
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: script
    skip_cleanup: true
    script: ./deploy/deploy.sh
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^master|development|test$
