sudo: required
language: java
jdk:
- openjdk11
services:
- docker
cache:
  directories:
  - "$HOME/.m2"
install:
- wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key |
  sudo apt-key add -
- echo "deb http://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
- sudo apt-get update -qq
- sudo apt-get install cf-cli -y --allow-unauthenticated
- wget https://archive.apache.org/dist/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.zip
- unzip -qq apache-maven-3.6.1-bin.zip
- export M2_HOME=$PWD/apache-maven-3.6.1
- export PATH=$M2_HOME/bin:$PATH
script:
- mvn --no-transfer-progress clean install
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
- provider: script
  skip_cleanup: true
  script: "./deploy/deploy.sh $CF_USERNAME $CF_PASSWORD $TRAVIS_BRANCH $DOCKER_USER
    $DOCKER_PASSWORD"
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^master|development|test$"
notifications:
  slack:
    secure: OpRX3GdEWi6Y4/d5nRfFWraFGfkvarT/ss5Gb44RRyUZ/ZgpDg6axwXD0PGcCTpxZOREwye+FoOUN3XHG5bImKbFPG0BBs7ey+KCvp2hmOvxJ+RLmPxIxBucPjB6G9VJa9UBwRrXsSELOzp4lWMOX2tuDl8XyvpCrdMOezGOOq1coN9Hh+Go7CNbXFjHfpgGOHEZUy8JBMjKWoCBFdxHf/GJYmnLh95Qc+pxWYmpcotiSuxX3Cz2v59oHBmuRGyMHa3Y3VnOPIWIMHbD4Ft+vDA6GkX1Zn3CMvgY05W/13LIQCzaINZ2uR5u2IFhoC+17No3CEas8ePfcF7NBs2RHthORUJtcOF9m0XigClYUm/urGFSTdtTiwEQCptGfr2wBLJ3QPC66ADzyWPvEwmXr9A01UnArMWtDhrW2QB7ErM9YNNVoZIuA+NC/pfk0rMiXaAlQHyNimP5zeS9YApZK1SYnTlgwG7iBAR0aMVCE8Ryqst8tYYL36GTiOXZoKLMgkmVub89i9a2wvJVHOlx3iCQhCD9moHFUsa7xSVRRe3/IgFG88Ro3C9x2BV5xFXQi7xwmxqxWFXIo/FvbV4mWZUcgiNmG9CcTkQwnpH/Q9vmPN9effsazan2Lz6QKAVu+gTmqNre0+UCLZ6j38gVYl1DVOq3UXTORPxlmMlcdM8=
