sudo: required
language: java
jdk:
  - openjdk11
services:
  - docker
cache:
  directories:
  - $HOME/.m2
install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.zip
  - unzip -qq apache-maven-3.6.1-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.6.1
  - export PATH=$M2_HOME/bin:$PATH
  - pip install --user awscli
script:
  - "./deploy/build.sh unused $TRAVIS_BRANCH"
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: script
    cleanup: false
    script: "./deploy/deploy.sh unused $TRAVIS_BRANCH"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^master|development|test$
