language: java
jdk:
  - openjdk11
services:
  - docker
cache:
  directories:
  - $HOME/.m2

install: true

script:
  - mvn clean package -DrepoToken=$COVERALLS_TOKEN coveralls:report

deploy:
  - provider: script
    script: mvn dockerfile:push -Ddockerfile.username=$DOCKER_USER -Ddockerfile.password=$DOCKER_PASSWORD
