sudo: required
language: java
jdk:
  - openjdk11
services:
  - docker
cache:
  directories:
  - $HOME/.m2

install:
  - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
  - echo "deb http://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
  - sudo apt-get update -qq
  - sudo apt-get install cf-cli -y --allow-unauthenticated

script:
  - mvn --batch-mode clean install -DrepoToken=$COVERALLS_TOKEN coveralls:report

deploy:
  - provider: script
    script:
      - mvn --batch-mode dockerfile:push dockerfile:push@push-image-latest -Ddockerfile.username=$DOCKER_USER -Ddockerfile.password=$DOCKER_PASSWORD
      - VERSION=$(mvn --batch-mode help:evaluate -Dexpression=project.version -q -DforceStdout)
      - ./deploy/deploy.sh $CF_USERNAME $CF_PASSWORD $TRAVIS_BRANCH $VERSION
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^master|development|test$
