sudo: required
language: java
jdk:
  - openjdk11
services:
  - docker
cache:
  directories:
  - $HOME/.m2
install:
  - sudo apt-get update -qq
  - sudo apt-get install cf-cli -y --allow-unauthenticated
  - wget https://archive.apache.org/dist/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.zip
  - unzip -qq apache-maven-3.6.1-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.6.1
  - export PATH=$M2_HOME/bin:$PATH
  - pip install --user awscli
  - mkdir ~/.aws
  - cp ./deploy/aws/* ~/.aws/
  - echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
  - echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
script:
  - mvn --no-transfer-progress clean install
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: script
    skip_cleanup: true
    script: ./deploy/deploy.sh
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^master|development|test$
