task:
  latex-input-dir: /app/doc
  latex-process-working-dir: /app/doc
  pdf-report: /app/doc/Main.pdf
  latex-process-command: make
mdm:
  endpoint: http://localhost:8080
  username: aerjaeklrj
  password: kajfja
logging:
  level:
    root: warn
    eu.dzhw.fdz.metadatamanagement: debug
