spring:
  cloud: 
    task:
      external-execution-id: ${cf.instance.index}
mdm:
  endpoint: ${vcap.services.mdm.credentials.endpoint}
  username: ${vcap.services.mdm.credentials.username}
  password: ${vcap.services.mdm.credentials.password}