task:
  latex-input-dir: input
  latex-process-working-dir: .
  pdf-report: output/report.pdf
mdm:
  endpoint: http://localhost:8080
  username: aerjaeklrj
  password: kajfja
logging:
  level:
    root: warn
    eu.dzhw.fdz.metadatamanagement: debug 
